import numpy as np
from scipy.ndimage import distance_transform_edt

MODALITY_CFG = {
    "T1":    {"transform": "linear", "p": (0.5, 99.5)},
    "T1CE":  {"transform": "linear", "p": (0.5, 99.8)},
    "T2":    {"transform": "linear", "p": (1.0, 99.0)},
    "FLAIR": {"transform": "linear", "p": (0.5, 99.7)},
    "PD":    {"transform": "linear", "p": (1.0, 99.0)},
    "DWI":   {"transform": "log1p",  "p": (0.1, 99.9)},
    "ADC":   {"transform": "linear", "p": (1.0, 99.0)},
    "SWI":   {"transform": "log1p",  "p": (1.0, 99.5)},
}


def _apply_transform(x, kind):
    if kind == "linear":
        return x
    
    if kind == "log1p":
        return np.log1p(np.maximum(x, 0))
    
    raise ValueError(f"Unknown transform: {kind}")


# Compute intensity percentiles for normalization
def get_percentiles(x, modality, mask=None, eps=1e-6):
    """
    x: 2D or 3D ndarray (float). Returns float32 in [0,1].
    modality: key in MODALITY_CFG
    mask: optional boolean mask selecting foreground voxels for percentile stats
    """
    # check if modality is valid
    modality = modality.upper()
    
    if modality not in MODALITY_CFG:
        raise ValueError(f"Unknown modality: {modality}. Supported modalities: {list(MODALITY_CFG.keys())}")
    
    cfg = MODALITY_CFG[modality]
    
    x = np.asarray(x).astype(np.float32)
    x = np.nan_to_num(x, nan=0.0, posinf=0.0, neginf=0.0) # handle NaN/Inf
    
    x_t = _apply_transform(x, cfg["transform"])
    
    if mask is None:
        # default foreground: nonzero
        mask = x_t > 0
    
    fg = x_t[mask]
    
    if fg.size == 0:
        return np.zeros_like(x_t, dtype=np.float32)
    
    # compute percentiles on foreground
    lo, hi = np.percentile(fg, cfg["p"])
    
    return lo, hi, mask


# Compute mean and std for normalization
def get_mean_and_std(img_volume: np.ndarray) -> np.ndarray:
    """Normalize image volume to zero mean and unit variance."""
    if img_volume.ndim not in {3, 4}:
        raise ValueError("Input image volume must be 3D or 4D array.")
    
    if img_volume.ndim == 4 and img_volume.shape[0] != 1:
        raise ValueError("4D image volume must have shape (1, D, H, W).")
    
    if img_volume.ndim == 4:
        img_volume = np.squeeze(img_volume, axis=0)
    
    # compute mean and std over non-zero regions
    mask = (img_volume != 0)
    mean = np.mean(img_volume[mask])
    std = np.std(img_volume[mask])
        
    return mean, std, mask


# Converts binary mask to SDF representation
class MedicalSDFEncoder:
    def __init__(self, normalize_per_instance: bool = True):
        """
        Args:
            normalize_per_instance (bool): 
                If True, scales the peak of *every* tumor to 1.0. This ensures small tumors 
                are just as visible to the model as large ones (crucial for BraTS).
                If False, preserves relative size (requires global dataset normalization).
        """
        self.normalize_per_instance = normalize_per_instance

    def mask_to_sdf(self, binary_mask: np.ndarray) -> np.ndarray:
        """
        Encodes a Binary Mask (0/1) into a 1-channel continuous SDF float image [0.0, 1.0].
        
        Args:
            binary_mask: 2D numpy array (H, W) with values 0 (background) and 1 (foreground).
            
        Returns:
            sdf_float: 2D numpy array (H, W) of type float32, range [0.0, 1.0].
        """
        # 1. Compute Euclidean Distance Transform
        # Calculates distance from every foreground pixel to the nearest background pixel.
        dist_map = distance_transform_edt(binary_mask)

        # 2. Handle Empty Masks (Slices with no tumor)
        max_val = dist_map.max()
        
        if max_val == 0:
            return np.zeros((binary_mask.shape[0], binary_mask.shape[1]), dtype=np.float32)

        # 3. Normalize to [0.0, 1.0]
        if self.normalize_per_instance:
            # Center of the tumor becomes 1.0 regardless of size
            sdf_map = dist_map / max_val
        else:
            # Raw distances (requires external normalization)
            sdf_map = dist_map
        
        sdf_float = sdf_map.astype(np.float32)

        return sdf_float

    def sdf_image_to_mask(self, sdf_image: np.ndarray, threshold: int = 0) -> np.ndarray:
        """
        Recovers the Binary Mask from the generated SDF Image.
        
        Args:
            sdf_image: 3D numpy array (H, W, 3) generated by the model.
            threshold: Pixel intensity (0-255) to consider as foreground. 
                       Usually 1 or higher filters out background noise.
        
        Returns:
            binary_mask: 2D numpy array (H, W) with values 0 and 1.
        """
        # 1. Average the channels (in case of slight generation variance across R, G, B)
        # Similar to InstructCV's inference strategy[cite: 789].
        grayscale_map = np.mean(sdf_image, axis=2)

        # 2. Thresholding
        # Any value > 0 implies it is "inside" the boundary distance.
        # We use > 1 to be robust against VAE noise (compression artifacts near 0).
        binary_mask = (grayscale_map > threshold).astype(np.uint8)

        return binary_mask
